trigger:
- main            # build every push to main

pool:
  vmImage: ubuntu-latest   # ← MS‑hosted agent, always available

variables:
  buildConfiguration: Release
  outputDir: $(Build.ArtifactStagingDirectory)

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '8.0.x'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build

- script: dotnet publish -c $(buildConfiguration) -o $(outputDir)
  displayName: Publish

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDir)'
    ArtifactName: drop
