# davi_quiz4_ci_dotnet
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches: [ main ]

pool:
  # Self‑hosted agent
  name: davi_pool        
  demands: java          

variables:
  buildConfiguration: Release
  outputDir: $(Build.ArtifactStagingDirectory)

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet publish -c $(buildConfiguration) -o $(outputDir)
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDir)'
    ArtifactName: 'drop'
