name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main              # ← simplest, one branch

# ── OR, fully expanded ──
# trigger:
#   branches:
#     include:
#       - main

pool:
  name: davi_pool    # or: ubuntu-latest
  # demands can be omitted or written as a list:
  # demands:
  #   - java

variables:
  buildConfiguration: Release
  outputDir: $(Build.ArtifactStagingDirectory)

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build

- script: dotnet publish -c $(buildConfiguration) -o $(outputDir)
  displayName: Publish

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDir)'
    ArtifactName: drop
